language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

install: pip install -r requirements.txt
env:
  - DEBUG = True SQLALCHEMY_DATABASE_URI = 'sqlite:///data.sqlite' SQLALCHEMY_TRACK_MODIFICATIONS = True
script: nosetests run.py runserver
